### ISSUE TITLE
64 bit with rip-record

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#2]
Hi NapoleonWilson,

Good morning(Night time for you probably), but that is a bummer there isnt a rip-record windows for 64 bit. Got a question, what if i went back to Linux(Ubuntu) would it work for 64 bit?

**Comment by NapoleonWils0n** [comment]
hi mate

yes the scripts on linux will run as 64 bit
and you can also install pilfer and rip-record on the same machine

**Comment by steve55792** [comment]
cool, back to Ubuntu(Linux). Which Ubuntu(Linux) do you think it would be easy to install on?

**Comment by NapoleonWils0n** [comment]
hi mate

ubuntu has now switched to using the gnome desktop instead of unity
and it uses the wayland display manager whe you log into the desktop instead of xorg

so ubuntu and debian now both run the gnome desktop 

but ubuntu does make a few changes from the gnome desktop compared to debian
like enabling icons on the desktoo and a few changes ti the colour scheme

ubuntu now uses the wayland display manager whe you log into the desktop
but kodi 17 doesnt work with wayland, kodi 18 will work with wayland

so when you get to the log in screen where you enter you username and password
you should see a little gear icon called session

if you click the gear icon you will get a drop down menu and you will see wayland is selected by default
you need to select xorg from the drop down menu befire you log in

otherwise kodi 17 wont run on ubuntu, you only need to change the setting the first time you log in
and then the system shoukd remember to log in with xorg and not wayland

watch the pilfer linux install to record from kodi video
which shows how to set up the latest version of ubuntu and change the display manager from wayland to xorg whe  you log in

i think the latest version of ubuntu with the gnome desktop will probably be easiest for you
just remember to log in using xorg and not wayland until kodi 18 is released

have a look at the pilfer linux install video before you do the install and it should make tjings easier
