### ISSUE TITLE
pilfer gui updated to 64bit  now at v4.0

### ISSUE THREAD

**Issue by t3rmin8tor** [NapoleonWils0n/pilfer#20]
hi mate  this isnt really an issue  just a rebuild of the gui 
now uses ffmpeg 64bit
rtmpdump 64bit
python36 64 bit 
git 64bit
now works with kodi 18.2 64bit which impliments cryptodome 

installer also now completely automated so it adds and removes all registry and desktop shortcuts

**Comment by NapoleonWils0n** [comment]
hi mate

thats very cool

ill have to use bootcamp and install windows on my macmini
and give it a go

i did try kodi 18 on the mac 
but found it keep listing all my tv series as having no episodes

so i switched back to kodi 17.6

**Comment by t3rmin8tor** [comment]
Hi mate  there is a bug in 18.2 64 bit that stops pilfer working if youre  watching the stream the window cant focus to run ffmpeg
But it  works if you right click the streams and use  play with dialog then save url or record

**Comment by NapoleonWils0n** [comment]
hi mate

thats a mad bug is that just on the windows version of kodi

im still running 17.6 on unix, linux and mac

setting up windows on the mac is a bit of a faffle with bootcamp

i did play around with the linux subsystem and installed an xorg server on windows
then you could launch linux gui apps

tried running mpv from linux subsytem and using xorg server on windows
it worked sort of no hardware acclerated video or any audio

been using the mac recently because i need to run a program called insta360 studio
which is program to import and edit 360 videos

mac mojave is so slow
my 8 year old laptop running freebsd with 4 gig of ram is faster than 4 year old macmini with 8 gig 

also the mac ships with a 12 year old version of bash, 
because the newer version uses gpl3 license which apple wont use

ive switched to using the zsh shell on unix linux mac
the mac actually ships with a current version of zsh so iswitched the shell from bash to zsh on the mac

**Comment by t3rmin8tor** [comment]
hi mate 

i have only tested on windows 10  so i have no idea if the bug is just windows related but its only the 64 bit 18.2 leia that has the bug  which is irritating because 32bit kodi doesnt have cryptodome so drm content is limited on 32bit

**Comment by t3rmin8tor** [comment]
hi mate update i have built  script.module.pycryptodome.zip  for 32bit so the drm content range is increased in kodi 17.6  and kodi 18.2 32bit  i will add the addon to my repo with instructions an how to apply the work around to dead addons that require cryptodome
