### ISSUE TITLE
pilfer record video working fine with Kodi 18.1 under Raspbian Stretch, no longer working with Kodi 18.6 under Raspbian Buster

### ISSUE THREAD

**Issue by tebokial** [NapoleonWils0n/pilfer#24]
Hi Napoleon,

I have been happily using your pilfer tool, mainly to record some documentaries of our  Belgian/Flemish public broadcast vrtnu that I would like to watch again in a few months (when the documentary has gone "off-line").   That is, within Kodi, I start the Kodi-addon VRTNU (an add-on which is also on github), and then, interactively, I press "y" on my keyboard, select the duration, and press "Ok" ... and wait for a few minutes for the video-file to appear on my Raspbian Desktop.  For some reason, this no longer works with the most recent Kodi 18.6 (which is only available for Raspbian Buster).   I am attaching 2 Kodi-log files (actually 2 times 2, i.e. once with and once with debug turned on in the Kodi system settings) : once for the working "Stretch" and for the non-working "Buster" version, each time with the same documentary from the VRTNU library.   

I would really appreciate if you could take a look at these logs : I did try so myself, but can't make much sense of it ...

[kodi_stretch.log](https://github.com/NapoleonWils0n/pilfer/files/4498800/kodi_stretch.log)

[kodi_stretch_debug.log](https://github.com/NapoleonWils0n/pilfer/files/4498799/kodi_stretch_debug.log)

[kodi_buster.log](https://github.com/NapoleonWils0n/pilfer/files/4498801/kodi_buster.log)

[kodi_buster_debug.log](https://github.com/NapoleonWils0n/pilfer/files/4498802/kodi_buster_debug.log)

**Comment by NapoleonWils0n** [comment]
Hi mate

glad you find pilfer useful
thanks for the log files 

i have figured out what the problem is with a bit of blunder around
i just installed kodi 18.6 on ubuntu

heres the fix

1 - move the cursor over a link in kodi so its highlighted

2 - press c on the keyboard

3 - select play using

4 - the play menu will appear

5 - select an option like save url, play or record from the menu and it will work

i checked and saving a url, playing with mpv and record from kodi work with the above fix

kodi must have changed something in kodi 18.6

ill do a video withe fix 

you may want to have a look at this site for tv episodes
https://newepisodes.co/

stay safe mate all the best
let me know if the fix works for you

**Comment by NapoleonWils0n** [comment]
hi mate

heres a video with the kodi 18.6 fix

https://www.youtube.com/watch?v=Q9WvY53D980
