### ISSUE TITLE
Kodi Matrix - Pilfer with playercorefactory

### ISSUE THREAD

**Issue by Sparkplugs** [NapoleonWils0n/pilfer#34]
Hi NapoleonWils0n,

Hope you're keeping well. It's been a long time since our last chat.
I was happily using Kodi Leia and recording programmes etc with playercorefactory until addons slowly died off and have moved onto the Kodi Matrix, which is fine and the addons that I use still work well. But, I could only get Matrix to work on Deepin V20 - flatpak run tv.kodi.Kodi.
The problem I'm having now is the ability to either bash record or pilfer the tv programmes using the playercorefactory.xml,
because the script will have changed and it can no longer locate or states no such directory.
Is it an easy fix for me to change the script so that it can find the new directory and continue recording tv programmes?
This is where its located:-
 "/home/plugs/.var/app/tv.kodi.Kodi/data/userdata/addon_data/pvr.stalker//cache.xml"

I probably haven't made myself very clear but please let me know if there's anything I can do or you'll probably need more info.

Many Thanks
SparkPlugs

**Comment by NapoleonWils0n** [comment]
Hi SparkPlugs good to hear from you mate

 basically you have kodi installed with flatpak on deepin


have you tried copying the playercorefactory.xml file to this folder
that should be the only change needed

/home/plugs/.var/app/tv.kodi.Kodi/data/userdata/

the playercorefactory.xml file always goes in the userdata folder


the only thing is flatpak uses a sandbox which can restrict file access
but i would have thought the playercorefactory.xml should carry on working because its use for external players

try copying the playercorefactory.xml file to 
/home/plugs/.var/app/tv.kodi.Kodi/data/userdata/

see if that works
otherwise it might be a flatpak issue

im not sure if theres a way to change the flatpak security settings for an app to it escape the sandbox

**Comment by Sparkplugs** [comment]
Hi NapoleonWils0n,

Thank you for your swift reply.
Yes, copied the xml file into the userdata folder but like you said it must be sandbox restricting the access. 
I’m going to try Kodi matrix on Debian 10 buster, apparently you can install it directly from Buster backports and see if I can get it all to work again. 

Thanks for your help, up the Hammers!

**Comment by NapoleonWils0n** [comment]
hi SparkPlugs, sounds like a flatpak sandbox issue
debian is a good distro and pretty stable

hope that sorts the problem out

my step dad is a hammers fan as well

im a newcastle fan, looks like we'll be the richest club in the world in the championship
:)

**Comment by Sparkplugs** [comment]
Ha ha Saudi Arabian, how bad! A few quid spare to snap up a few decent players from the other wealthy clubs.
