### ISSUE TITLE
overwritten

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#37]
Hi NapoleonWilson, how have you been? I've got pilfer recording one after another automatically, I was wondering is how would I make it so it won't overwrite one another? I think I'm not sure you mentioned it before about overwriting in one of your videos but not sure.
                                                                                                                           Steve

**Comment by NapoleonWils0n** [comment]
hi steve

good to hear from you mate, im not so bad

pilfer should automatically create a file name with the date and time

but if its not creating a new file for each stream with the date and time
it may be because of the way you have got pilfer to record the streams one after another in your batch script

you need a way to create a unique file name on windows so that the previous file isnt overwritten
i find adding the date and time with seconds is the best way to do that

but i dont know how to write batch scripts and i cant get windows 11 working i a vm at the moment
so i havent got a way to test anything out on the windows side

if you have google for something like

windows add date and time to file name

you'll get some results 

i found this article about creating file names with date and time in a windows batch script
i guess thats might do the job

https://tecadmin.net/create-filename-with-datetime-windows-batch-script/

hope that helps mate

**Comment by steve55792** [comment]
Lol, I just decided togo back to Ubuntu  once again with their Latest 22.04 Jellyfin(if thats what they call it.) But when i play Kodi 19.4 the video freezes(kodi freezes). Not sure why it does that, i read somewhere it might be the python part in Ubuntu. just curious if i should go back  earlier version of Ubuntu or Kodi? How would I downgrade on either one? Hmm, I think in here we mentioned before in the messages.

**Comment by NapoleonWils0n** [comment]
HI Steve 

The version of Kodi in the Ubuntu repositories doesnt have all of features enabled 
like support for videos that use drm and rtmp streams

What you want to do is uninstall the version of Kodi that comes with Ubuntu
by running this command

```
sudo apt remove kodi
```

Then follow the instructions on this page to use the offical ppa to install the latest version of kodi
with support for drm and rtmp streams

Kodi ppa instructions
https://github.com/NapoleonWils0n/cerberus/blob/master/kodi/kodi-ppa.org


Heres the video showing all the steps to install the latest version of Kodi using the offical ppa

Kodi ppa youtube
https://www.youtube.com/watch?v=LajY2mTbrEA


This will install the latest version of Kodi with more features enabled

Let me know if you get stuck on anything

**Comment by steve55792** [comment]
How do i remove broken dependcies, the kodi-inputstream-adaptive kodi-inputstream-rtmp  are broken from the before kodi.

**Comment by NapoleonWils0n** [comment]
Hi Steve

to remove the broken dependcies

run the following command

```
sudo apt remove kodi-inputstream-adaptive kodi-inputstream-rtmp
```

then run autoremove as well for good measure

```
sudo apt autoremove
```

hope that fixes the issue
