### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#39]
Good morning,

Not sure if tr3mina8tor still with this project for windows, I was wondering if you know what this means and how to fix it:

Traceback (most recent call last):
  File "C:\pilfer\system\bin\pilfer-gui.pyw", line 2, in <module>
    import tkinter.ttk, os, datetime, getpass
ImportError: No module named tkinter.ttk

                                                                                                                                          steve

**Comment by NapoleonWils0n** [comment]
hi steve

i havent spoken to the t3rmin8tor in ages

from the error it sound like tkinter isnt installed
tkinter is a python library, i think for building gui apps

if you google 
windows install tkinter

there are quite a few links
but im not sure if you need to install tkinter in the same folder as pilfer

im not sure if you could install tkinter with python and pilfer would pick it up
i suppose you just need to put the tkinter.tkk file in the pilfer folder to fix the error

i dont know how the t3rm8tor build the app on windows
but i think you just need to find a way to put the tkinter.tkk file in the pilfer folder

**Comment by steve55792** [comment]
I found out if i use python 2.7, it still give the error but if i use python higher than that it wont give that error. Still having issues with using  windows 10 of tr3mn8tor's, I'm still using Ubuntu 22.04  rip-record-batch, it works but it won't save or record from kodi. Lol, the only reason why i still have windows 10 on this computer is cause of a game called star stable my daughter plays when Daddy  isn't on here. Lol.

**Comment by NapoleonWils0n** [comment]
HI Steve, maybe it was the python version that was the issue then.

As an alternative to rip-record-batch which is really old,
you could use a program called task-spooler with pilfer

task-spooler lets you create a queue of commands to run,
so it runs the first command and when thats finished it runs the next command in the queue and so on

so you can create a queue of pilfer commands to run one after another

to add a command to the task-spooler queue,
just add tsp before the command

for example when you run pilfer on the command line with a url it looks like this

`pilfer -i 'video url'`

or using a text file

`pilfer -i 'video-url.txt'`


to add a pilfer url on the command line to the task-spooler queue just add tsp before pilfer

`tsp pilfer -i 'video url'`

to add a pilfer text file on the command line to the task-spooler queue just add tsp before pilfer

`tsp pilfer -i 'video-url.txt'`

this should let you create a queue of pilfer commands to run 
either using urls or text files on the command line

i have also included code to add to your playercorefactory.xml file 
that will let you queue up videos to record from kodi using task-spooler and pilfer


install task-spooler on ubuntu

`sudo apt install task-spooler`

the program is called task-spooler
but the actual command you run is called tsp


to view the task spooler queue on the command line 

just run tsp in the terminal

`tsp`

to cleat the queue of finished items run

`tsp -C`


to view the output of current command 
for example to see the output of the pilfer command that is recording a video

just run

`tsp -c`

this will show you the command that is running in the queue
just like when you run a command in the terminal

to exit viewing the current command that is running in the queue just press 
ctrl c

so hold the control button and then press c
this wont kill the command that is running in the terminal
it just exits task-spooler and returns you back to the terminal

normally pressing control c in the terminal kills the command that is being run
but when you run 

`tsp -c`

to view the task-spooler command being run
and then press control c it just returns you to the terminal and doesnt kill pilfer

also note that tsp -c with a lowercase c shows the command being run

`tsp -c`

but tsp -C with an uppercase C clears all the finished items in the task-spooler queue

`tsp -C`

and of course read the task-spooler manual

`man tsp`


playercorefactory.xml task-spooler and pilfer

try add this code block to your playercorefactory.xml file
that should let you queue up videos to record from kodi using task-spooler and pilfer

`
   <player name="record video queue" type="ExternalPlayer" audio="false" video="true">
	<filename>tsp "$HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" &</args>
     <hidexbmc>false</hidexbmc>
   </player>  
   <player name="record video - 30 minutes queue" type="ExternalPlayer" audio="false" video="true">
	<filename>tsp "$HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 00:30:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
   <player name="record video - 1 hour queue" type="ExternalPlayer" audio="false" video="true">
	<filename>tsp "$HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 01:00:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
   <player name="record video - 2 hours queue" type="ExternalPlayer" audio="false" video="true">
	<filename>tsp "$HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 02:00:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
   <player name="record video - 3 hours queue" type="ExternalPlayer" audio="false" video="true">
	<filename>tsp "$HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 03:00:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
`

have a look at this video by gotbletu that shows how to use task-spooler

[task spooler gotbletu youtube video](https://www.youtube.com/watch?v=wv8D8wT20ZY)

you can also use task-spooler to create a list of videos to play with mpv

[sauron script youtube](https://www.youtube.com/watch?v=8ERilbi2lu0l)

sauron script using task-spooler

[sauron script](https://raw.githubusercontent.com/NapoleonWils0n/ubuntu-bin/master/sauron)


hopefully using task-spooler and pilfer either on the command line or from within kodi
will let you queue up videos to record instead of using rip-record-batch

the other advantage of task-spooler is you can see the queue 
and how many videos have finished recording

hope that makes sense

**Comment by steve55792** [comment]
Hi NapoleonWilson,

Thank you for helping me, I appreciate it. Ill try this new way of yours, looks exciting. Im guessing too that i have to unistall rip-record before i install this?

**Comment by NapoleonWils0n** [comment]
hi steve you dont need to uninstall rip-record

just install task-spooler with

```sudo apt install task-spooler```

**Comment by steve55792** [comment]
Thank you

**Comment by steve55792** [comment]
add the code block at the beginning or at the end right before the  

   
   
   
   
 </rules>
</playercorefactory>

**Comment by NapoleonWils0n** [comment]
hi mate, you mean the code block to add to the playercorefactory. xml file

just add the code before the closing players tag
towards the bottom of the file

```
</players>
```

**Comment by steve55792** [comment]
hi napoleonwilson, for some reason  the pilfer not grabbing the link or saving the url in kodi, but i do have the code block in the right spot.

**Comment by NapoleonWils0n** [comment]
hi mate

its the flatpak version of kodi thats stopping the scriot running

i had the same sort of issue with the flatpak version of firefox not open magnet links for torrents

if you want to use the script from within kodi you have to switch from the flatpak version

and install kodi using the ppa which will install the latest version of kodi
and other stuff that doesnt come with kodi from the standard 

[kodi ppa install](https://youtu.be/LajY2mTbrEA)

**Comment by steve55792** [comment]
Hi, 
The only reason I use Flatpak version  is it doesnt freeze and close unexpectedly.  I'll go ahead  and unistall flatpack and reinstall  kodi with ppa. Did we talked about before about freezing up  and python issues.

**Comment by steve55792** [comment]
Kodi is running ok now and pilfer is saving url and recording inside of kodi for some reason when i had my vpn on, it didnt work but when i  turned it off , it finally worked. Now I'm gonna try the task spooler thing.

**Comment by NapoleonWils0n** [comment]
HI Steve, i havent had any issues with kodi freezing

you may need to start with a fresh .kodi folder and reinstall your addons
and playercorefactory.xml file

you could just move your current .kodi to the desktop,
and then start up kodi and it will create the .kodi folder then just reinstall your addons and playercorefactory.xml

that way you wont have any issues with addons not working properly

if you want to downgrade you need to uninstall kodi you installed with the ppa

`sudo apt remove kodi`

here how to remove the ppa

[remove ppa](https://www.omgubuntu.co.uk/2019/12/how-to-remove-ppa-ubuntu)

then do an update

`sudo apt update`

and an upgrade

`sudo apt upgrade`

and then install kodi from the ubuntu repo

`sudo apt install kodi`

**Comment by NapoleonWils0n** [comment]
HI Steve, cant think why the vpn would stop record thats odd

**Comment by steve55792** [comment]
Hi Napoleonwilson,  on second thought maybe its not the vpn, cause im having kodi freezing up again, starting to be a pain lol.
Which Kodi version do you have?

**Comment by steve55792** [comment]
Hi Napoleonwilson,

I haven't tried moving kodi folder to the desktop yet, I reinstalled kodi again after removing ppa part. See if it freezes again.

**Comment by NapoleonWils0n** [comment]
hi steve
the .kodi folder contains that can be specific to a certain version of kodi

so if you run a version of kodi that is different to the one that created the .kodi folder
it may have the weong version of python files for the version younare running

**Comment by steve55792** [comment]
HI NapoleonWilson,

 I moved the kodi folder to the desktop and restarted kdi with a new kodi folder and everything is working good so far, no freezing  and everything from saving url and recording inside kodi is working.  I am going to play around with task spooler and i watchedthe video of it and there is alot a person can do than what you can do in windows. Thank you for your help.

**Comment by NapoleonWils0n** [comment]
hi steve, i thought the freezing might be of an old .kodi folder
and not something wrong with your system

glad you got everything working

have a player around with task-spooler and i think youll find it really usefull to create queues of videos to download

**Comment by steve55792** [comment]
when i use inside kodi the task-spooler, it doesnt add to the queue but when i do it by saving the url(onto the desktop) ones then it works.

**Comment by NapoleonWils0n** [comment]
Hi Steve, my bad 
the reason its wasnt working on Kodi is i should have put tsp command inside the double quotes in the playercorefactory.xml

the tsp command should have been inside the double quotes like this

```
<filename>"tsp $HOME/.local/bin/pilfer"</filename>
```

and not like this

```
<filename>tsp "$HOME/.local/bin/pilfer"</filename>
```

Heres working block of code for task spooler and pilfer for your playercorefactory.xml file
i just tested it and it works perfectly 

```
   <player name="record video queue" type="ExternalPlayer" audio="false" video="true">
	<filename>"tsp $HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" &</args>
     <hidexbmc>false</hidexbmc>
   </player>  
   <player name="record video - 30 minutes queue" type="ExternalPlayer" audio="false" video="true">
	<filename>"tsp $HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 00:30:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
   <player name="record video - 1 hour queue" type="ExternalPlayer" audio="false" video="true">
	<filename>"tsp $HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 01:00:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
   <player name="record video - 2 hours queue" type="ExternalPlayer" audio="false" video="true">
	<filename>"tsp $HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 02:00:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
   <player name="record video - 3 hours queue" type="ExternalPlayer" audio="false" video="true">
	<filename>"tsp $HOME/.local/bin/pilfer"</filename>
     <args>-i "{0}" -t 03:00:00 &</args>
     <hidexbmc>false</hidexbmc>
   </player> 
```

you can just edit your playercorefactory.xml and fix the typo or delete the code you added
and add the new code

let me know if that works for you

**Comment by NapoleonWils0n** [comment]
Hi Steve

ive just upload a new playercorefactrory.xml to the pilfer repo with the task spooler commands 

here the link so you can download the file

[taskspooler playercorefactory.xml](https://raw.githubusercontent.com/NapoleonWils0n/pilfer/master/playercorefactory/linux-unix/pilfer-taskspooler/playercorefactory.xml)

**Comment by NapoleonWils0n** [comment]
Hi Steve, im just uploading a video about pilfer and task spooler

**Comment by steve55792** [comment]
Hi NapoleonWilson, nice job and awesome video on the subject. So a person can actually download from archive.org without getting in trouble? A person can find some good stuff on there.
