### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#42]
Good Morning NapoleonWilson,

 I was wondering if there was anything changed with pilfer cause when i try to use it in kodi, it doesn't show up even  if ya type c or y for the menu. I have the playercorefactory xml in the userdata folder in ubuntu 22.04. I'm gonna try windows 10 and see if it has the same issue.  
I even refresh kodi.
                                                                                                                                                        Thank You
                                                                                                                                                           Steve

**Comment by NapoleonWils0n** [comment]
hi steve, nothing has changed with pilfer there havent been any updates

i havent had anyone else mention any issues with the playercorefactory.xml menu not showing up
and i cant find anything online about any changes to kodi and the playercorefactory.xml file

kodi did change the keys you had to press in 18.6 to c as you mentioned
i dont think they have changed the key again

i wonder if its an issue with your kodi profile

have you tried moving the kodi profile to the desktop and the  restarting kodi so it creates a new profile
then adding the playercorefactory.xml file

let me know if you figure out what the issue is

**Comment by NapoleonWils0n** [comment]
Hi Steve, i just set up a vm and installed ubuntu 22.04 and kodi
and copied the playercorefactory.xml file to ~/.kodi/userdata

i installed an addon in kodi went into the addon pressed c on a link
then selected play using which brought up the playercorefactory.xml menu

i selected save url and it saved the url to the desktop

so no issues with ubuntu 22.04 and kodi my end

must be something with your setup thats causing the issue

**Comment by steve55792** [comment]
Hi NapoleonWilson:

 Found the issue, there was a space between the period and the xml: it was like this  playercorefactory .xml

**Comment by NapoleonWils0n** [comment]
hi steve, good catch
have to laugh

**Comment by steve55792** [comment]
Thank you. A person can be surprise like a little small error like that would cause.  I had to laugh also.  Be cool if the tsp filter part would work on windows Operating systems  also but  sometimes i prefer Ubuntu over Windows  half of the time.

**Comment by NapoleonWils0n** [comment]
hi steve, its easy to make mistakes like that and then spend ages trying to figure what the problem is
but at least its an eay problem to fix

task spooler is one of my fav apps, but i dont know of any simmilar windows apps
