### ISSUE TITLE
Struggeling getting Pilfer run on MacOS with Python 3.9.7 and ffmpeg

### ISSUE THREAD

**Issue by WolfMalte** [NapoleonWils0n/pilfer#43]
Struggeling with getting the pilfer skript running:

-----------------------------------
having the following configuration:
-----------------------------------

- xxx bin % python
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

- xxx % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026

- xxx bin % ffmpeg -version
ffmpeg version N-110057-g1e406692e5-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 11.0.0 (clang-1100.0.33.17)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      58.  4.100 / 58.  4.100
libavcodec     60.  6.101 / 60.  6.101
libavformat    60.  4.100 / 60.  4.100
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  4.100 /  9.  4.100
libswscale      7.  2.100 /  7.  2.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100
xxx bin % 

----------------------------------

- xxx bin % ./pilfer -i 'https://www.youtube.com/watch?v=nsClEkgPi7A'
running ffmpeg command:

- xxx bin % 

--------------------------------
any idea why this is hapening and why the ffmpeg does not start working?
Thank you very much in advance.

Regards, WolfMalte

**Comment by NapoleonWils0n** [comment]
Hi Mate, sorry you having a bit of bother getting pilfer working on the mac

apple changes the location of the python directory each time there is an update,
so you may need to change the path to python in a couple of places

on the mac you need to either have ffmpeg installed in your home bin directory,
or create a symlink from where ffmpeg is installed to the bin directory
ill take you through the steps

if you run 

`
pilfer -h
`

does it show the pilfer help menu in the terminal
if it does pilfer is install and the issue is the path to ffmpeg

try going through these steps so we can resolve the issue

create a bin directory in your home if you dont have one

`
mkdir -p ~/bin
`

if you are using the bash shell you need to add the following code to your ~/.bashrc

`
if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
fi
`

you also need to add the path to python 
check in your home library python to check if the python directory is called Python/3.9 or Python 3.9.7
and change the path below

`
if [ -d "$HOME/Library/Python/3.9/bin" ] ; then
        PATH="$HOME/Library/Python/3.9/bin:$PATH"
fi
`

and then source your ~/.bashrc

`
source ~/.bash_profile
`

if you are using zsh add the following to your ~/.zshenv file

`
typeset -U PATH path
path=("$HOME/bin" "$HOME/.local/bin" "$path[@]")
export PATH
`

try adding the following to your ~/.zshrc for python
you also need to add the path to python 
check in your home library python to check if the python directory is called Python/3.9 or Python 3.9.7
and change the path below

`
if [ -d "$HOME/Library/Python/3.9/bin" ] ; then
        PATH="$HOME/Library/Python/3.9/bin:$PATH"
fi
`

then source your ~/.zshenv file

`
source ~/.zshenv
`

and source your ~/.zshrc file

`
source ~/.zshrc
`

If you dont have ffmpeg installed in your home bin directory like this

`
~/bin/ffmpeg
`

you can create a symbolic link from where ffmpeg is installed to your home bin directory

first check where ffmpeg is installed by running the following command

`
which ffmpeg
`

ffmpeg should be installed somewhere like /usr/local/bin/ffmpeg

create a symbolic link from where ffmpeg is installed to the bin directory in your home

if ffmpeg is installed somewhere else change the /usr/loca/bin/ffmpeg path in the command below

`
ln -s /usr/local/bin/ffmpeg $HOME/bin
`

the other issue on the mac is the path to python changes with each new version
so you also need to edit the playercorefactory.xml

[playercorefactory.xml](https://raw.githubusercontent.com/NapoleonWils0n/pilfer/master/playercorefactory/mac/python-3.7/playercorefactory.xml)

and do a search and replace to change the path from python 3.7

<filename>/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7</filename>

to python 3.9

<filename>/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9</filename>


check that ffmpeg is working by running ffmpeg with the -version option

`
ffmpeg -version
`

might also be a good idea to do a reboot just so it picks up any changes in your shell config

after a reboot try running pilfer again on the command line


`
pilfer -i 'https://www.youtube.com/watch?v=nsClEkgPi7A'
`

and cross your fingers for good luck
hopefully that should resolve the issue of pilfer not finding ffmpeg

if you get stuck on anything or need a bit more help let me know

Im guessing by the way you write script as skript your German,
also the name wolf sounds a bit German 

A collection of ffmpeg shell scripts for basic editing tasks
i translated all the scripts into German

[fmpeg-Skripte](https://github.com/NapoleonWils0n/ffmpeg-Skripte)

Heres the English version

[ffmpeg-scripts](https://github.com/NapoleonWils0n/ffmpeg-scripts)

pilfer mac install instructions
[pilfer mac install](https://github.com/NapoleonWils0n/pilfer#ffmpeg-install)

**Comment by NapoleonWils0n** [comment]
HI Mate, pilfer wont work with youtube links

for youtube links you want [yt-dlp](https://github.com/yt-dlp/yt-dlp)

**Comment by WolfMalte** [comment]
any idea what I can change to get the recording running?

**Comment by WolfMalte** [comment]
where does pilfer if working save the recordings by default (Desktop?)
Thank you very much fpr your help.
Kind Regards,
Malte

**Comment by WolfMalte** [comment]
<img width="804" alt="Bildschirmfoto 2023-03-27 um 15 32 44" src="https://user-images.githubusercontent.com/128829465/227953231-434d43c3-9fe9-4300-a894-4903ccda65df.png">

**Comment by WolfMalte** [comment]
is this here the problem? Sorry for texting so much on your github :D

**Comment by NapoleonWils0n** [comment]
HI Mate, dont worry about raising issues on github thats not a problem

it looks like you have pilfer installed properly becuase it can record the tears of steel m3u8 link

pilfer does pick up things like cookies from kodi urls 
so in theory if you can play the video in Kodi you can record it as long as the video isnt using drm

could you save the url from kodi you are having problem with and email here
danieljwilcox@gmail.com

probably better to talk about this over emil rather than on github
cheers mate

**Comment by NapoleonWils0n** [comment]
Just deleting my email from the thread
