### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#46]
Good Morning Sir: I updated my Ubuntu to 23.04(whatever the new one is).  I forgot my username, Lol.  Is there a way to retrieve  the username after upgrading. I remember my password easily but for the username ummmmmmm grew a blank at the beginning of ubuntu 23.

                                                                                                                            Thank you
                                                                                                                                steve

**Comment by NapoleonWils0n** [comment]
Hi Steve, thats a classic its usually the password people forget

heres how you can out what your username is on linux in a couple of steps

If you cannot remember the Ubuntu username, you can display a list of all users for the system

1 - To do this, restart the machine, press "Shift" at the GRUB loader screen, select "Rescue Mode" and press "Enter." 

2 -  Select the Root Shell option.

3 -  Type in this command into the terminal window that opens:

`
awk -F: '$3 == 1000' /etc/passwd
`

4 - Your username will be at the very beginning of the line on one of the returned lines. 

5 - Reboot into normal mode and use the username specified.

hope that helps mate

**Comment by steve55792** [comment]
Hi NapoleonWilson, No luck cause it says no file or no directory after i typed in the command:  awk -F: '$3 == 1000' /etc/passwd.
I might reinstall ubuntu after I unistall the Volume where  Ubuntu is located. Start fresh.

**Comment by steve55792** [comment]
Good morning, Dandere2x looks interesting to play around with but i figure out why i have to boot into ubuntu recovery because when i try to boot ubuntu normally this error shows:   [0.00000] ---[end kernel panic - not syncing:timer doesn't work through Interrupt-remapped IO-APIC ]---.  Weird.

**Comment by NapoleonWils0n** [comment]
Hi Steve, i found a couple of posts describing the issue your having which seems to happen on older computers

It looks like you have to edit the grub file and add some extra options

[12-04-kernel-panic-not-syncing-io-apic-timer-doesnt-work](https://askubuntu.com/questions/372187/12-04-kernel-panic-not-syncing-io-apic-timer-doesnt-work)

from the above link

When you first start Ubuntu you need to press the escape key and append "noapic nolapic acpi=off" to the boot options. Your computer is an older model apic isn't compatible with it. My dad's computer is the same way. If you ever get around to installing it on your harddrive you're going to have a doosy. You'll have to go into a liveCD, mount your harddrive as if you were actually using it and then edit your bootloader.

heres some links on youtube that should show you how to use a live cd and mount your hard drive and edit your grub

https://www.youtube.com/results?search_query=ubuntu+live+cd+edit+grub

i had issues with ubuntu 23.04 on my old macbook air 2011,
because the linux kernel 6 doesnt work with the wifi card and causes the computer to lock up

is your computer quite old, if so it might be that like my old mac it might have issue with the newer version of ubuntu

**Comment by steve55792** [comment]
probably like around 5 years old, not that old.
