### ISSUE TITLE
Pilfer plays but won't record or save url

### ISSUE THREAD

**Issue by bumblingalong** [NapoleonWils0n/pilfer#51]
Love your work on this. I had the pre-Pilfer version working a few years ago and have just come back to this.

I have tried to follow the instructions (Win10) carefully but I'm no expert - as you can tell from my username!

"y" invokes the menu just fine and , if I select the Play option, the Kodi stream is played in mpv.

However, if I try to save the url, the video stream pauses, then there is a bit of screen shudder, followed by the "External player is active box with the message "Press 'OK' when playback has ended". Nothing is saved to the desktop.

Any record option pauses playback, briefly opens a command window (which I'm pretty sure is invoking ffmpeg, though it disappears very quickly, and then flips out to the "External player is active box with the message "Press 'OK' when playback has ended". Nothing is saved to the desktop.

I saw another thread a bit like this, where write permissions seemed to be the issue, but I'm not sure whether that is relevant?

Any suggestions?

**Comment by bumblingalong** [comment]
After a bit more snooping about write permissions in Win10, maybe this would be helpful?

![image](https://github.com/NapoleonWils0n/pilfer/assets/53836151/c6337af6-3a37-4b7f-9288-3ca08045ee0e)

**Comment by NapoleonWils0n** [comment]
HI Mate, did you install pilfer using the windows installer

https://github.com/t3rmin8tor/pilfer-installer

i didnt write the windows installer, and im not a windows user
it may be an issue with windows path not finding the scripts

whats in your windows system path

i know the scripts work on the latest version of kodi on linux

when you are over a link in kodi you need to press c
and play using and then record, the way the menu works changed in kodi 18.6 from memory

have a look at this video if you havent already

https://odysee.com/@NapoleonWils0n:6/kodi-18-6-playercorefactory-xml-fix:8

i had to remove all the kodi videos from youtube because youtube keep taking them down
after they had been on youutube for over 5 years with no problems

i sync all the video to odysee here 
https://odysee.com/@NapoleonWils0n:6

let me know how you get on
