### ISSUE TITLE
Pilfer won't run under linux cron job

### ISSUE THREAD

**Issue by backyard-bbq** [NapoleonWils0n/pilfer#53]
I am trying to setup a pilfer cron job under arch linux arm64 on a Rpi5. For some reason, I cannot get pilfer to work when set in a cron job. Even a simple one like /home/alarm/.local/bin/pilfer -h > /home/alarm/Desktop/pilfer.txt produces an empty file but if you d it from a terminal it works. What am I missing?

**Comment by NapoleonWils0n** [comment]
hi mate, im havent tried using pilfer with cron
so not sure what the issue is off the top of my head

but i have a better way to schedule recording with the at command on linux and mac

https://odysee.com/@NapoleonWils0n:6/schedule-commands-to-be-run-later-with:0

https://odysee.com/@NapoleonWils0n:6/mac-schedule-recording-with-the-at:a

https://github.com/NapoleonWils0n/cerberus/blob/master/at/at.org

se if that works for you

**Comment by backyard-bbq** [comment]
I figured it out. I was running pilfer from when I installed pilfer when I had python 3.11. I now have python 3.12. Pilfer worked from terminal but not a script so I couldn't figure it out. I ran a cron shell and figured it out. I reinstalled pilfer and it installed with python 3.12. Now it is working. Ugh, don't upgrade lol.
