### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated

### ISSUE THREAD

**Issue by sumitdipsite2005** [NapoleonWils0n/pilfer#54]
When I call pilfer on a saved url file I get this warning error. I am on mac. It used to work fine last year. Haven't used it in a while.

/Library/Python/3.7/bin/pilfer:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
running ffmpeg command:

And then the command exits.

Any help on fixing this? Thanks.

**Comment by sumitdipsite2005** [comment]
I updated from python fro 3.7 to 3.11. The above error is gone but still unable to get pilfer running.

Upon calling pilfer: It shows below and then exits.
running ffmpeg command:

**Comment by NapoleonWils0n** [comment]
hi mate

your right

i have the same issue on python 3.11, i dont get any error message either

last time i used pilfer was earlier this year so the issue must have happened recently

thanks for showing the error message that helps narrow things down a bit
from the error it looks like it might be related to the setup.py

https://github.com/NapoleonWils0n/pilfer/blob/master/setup.py

and the entry_points 

i havent written any python in 7 years since i wrote pilfer
so havent really kept up on any python api changes

ill look into it

**Comment by NapoleonWils0n** [comment]
hi mate

i have created a new version of pilfer called pilfer-3
which uses a pyproject.toml file 

which seems to have solved this issue

running ffmpeg command:
And then the command exits.

ffmpeg starts and records the url

can you try uninstalling pilfer

and then installing pilfer-3 using a python virtual env

https://github.com/NapoleonWils0n/pilfer-3?tab=readme-ov-file#virtual-env
